/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTrackClickRouteImport } from './routes/api/track-click'
import { Route as ApiRefinePackageRouteImport } from './routes/api/refine-package'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackClickRoute = ApiTrackClickRouteImport.update({
  id: '/api/track-click',
  path: '/api/track-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefinePackageRoute = ApiRefinePackageRouteImport.update({
  id: '/api/refine-package',
  path: '/api/refine-package',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/chat': typeof ApiChatRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/chat' | '/api/refine-package' | '/api/track-click'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/chat' | '/api/refine-package' | '/api/track-click'
  id:
    | '__root__'
    | '/'
    | '/api/chat'
    | '/api/refine-package'
    | '/api/track-click'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiRefinePackageRoute: typeof ApiRefinePackageRoute
  ApiTrackClickRoute: typeof ApiTrackClickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-click': {
      id: '/api/track-click'
      path: '/api/track-click'
      fullPath: '/api/track-click'
      preLoaderRoute: typeof ApiTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refine-package': {
      id: '/api/refine-package'
      path: '/api/refine-package'
      fullPath: '/api/refine-package'
      preLoaderRoute: typeof ApiRefinePackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiChatRoute: ApiChatRoute,
  ApiRefinePackageRoute: ApiRefinePackageRoute,
  ApiTrackClickRoute: ApiTrackClickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
