/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransferRouteImport } from './routes/transfer'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BuchenRouteImport } from './routes/buchen'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as ApiTrackClickRouteImport } from './routes/api/track-click'
import { Route as ApiRefinePackageRouteImport } from './routes/api/refine-package'
import { Route as ApiItineraryWeatherRouteImport } from './routes/api/itinerary-weather'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransferRoute = TransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BuchenRoute = BuchenRouteImport.update({
  id: '/buchen',
  path: '/buchen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackClickRoute = ApiTrackClickRouteImport.update({
  id: '/api/track-click',
  path: '/api/track-click',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRefinePackageRoute = ApiRefinePackageRouteImport.update({
  id: '/api/refine-package',
  path: '/api/refine-package',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItineraryWeatherRoute = ApiItineraryWeatherRouteImport.update({
  id: '/api/itinerary-weather',
  path: '/api/itinerary-weather',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buchen': typeof BuchenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/transfer': typeof TransferRoute
  '/api/chat': typeof ApiChatRoute
  '/api/itinerary-weather': typeof ApiItineraryWeatherRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buchen': typeof BuchenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/transfer': typeof TransferRoute
  '/api/chat': typeof ApiChatRoute
  '/api/itinerary-weather': typeof ApiItineraryWeatherRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/buchen': typeof BuchenRoute
  '/impressum': typeof ImpressumRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/transfer': typeof TransferRoute
  '/api/chat': typeof ApiChatRoute
  '/api/itinerary-weather': typeof ApiItineraryWeatherRoute
  '/api/refine-package': typeof ApiRefinePackageRoute
  '/api/track-click': typeof ApiTrackClickRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buchen'
    | '/impressum'
    | '/login'
    | '/register'
    | '/transfer'
    | '/api/chat'
    | '/api/itinerary-weather'
    | '/api/refine-package'
    | '/api/track-click'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buchen'
    | '/impressum'
    | '/login'
    | '/register'
    | '/transfer'
    | '/api/chat'
    | '/api/itinerary-weather'
    | '/api/refine-package'
    | '/api/track-click'
  id:
    | '__root__'
    | '/'
    | '/buchen'
    | '/impressum'
    | '/login'
    | '/register'
    | '/transfer'
    | '/api/chat'
    | '/api/itinerary-weather'
    | '/api/refine-package'
    | '/api/track-click'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BuchenRoute: typeof BuchenRoute
  ImpressumRoute: typeof ImpressumRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TransferRoute: typeof TransferRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiItineraryWeatherRoute: typeof ApiItineraryWeatherRoute
  ApiRefinePackageRoute: typeof ApiRefinePackageRoute
  ApiTrackClickRoute: typeof ApiTrackClickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transfer': {
      id: '/transfer'
      path: '/transfer'
      fullPath: '/transfer'
      preLoaderRoute: typeof TransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buchen': {
      id: '/buchen'
      path: '/buchen'
      fullPath: '/buchen'
      preLoaderRoute: typeof BuchenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-click': {
      id: '/api/track-click'
      path: '/api/track-click'
      fullPath: '/api/track-click'
      preLoaderRoute: typeof ApiTrackClickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/refine-package': {
      id: '/api/refine-package'
      path: '/api/refine-package'
      fullPath: '/api/refine-package'
      preLoaderRoute: typeof ApiRefinePackageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/itinerary-weather': {
      id: '/api/itinerary-weather'
      path: '/api/itinerary-weather'
      fullPath: '/api/itinerary-weather'
      preLoaderRoute: typeof ApiItineraryWeatherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BuchenRoute: BuchenRoute,
  ImpressumRoute: ImpressumRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TransferRoute: TransferRoute,
  ApiChatRoute: ApiChatRoute,
  ApiItineraryWeatherRoute: ApiItineraryWeatherRoute,
  ApiRefinePackageRoute: ApiRefinePackageRoute,
  ApiTrackClickRoute: ApiTrackClickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
